language: java

jdk: openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never
    on_failure: always

env:
  global: CODECOV_TOKEN="dd478a8e-f26f-4b36-b075-222a797373dc"